name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu,x86_64-apple-darwin

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Build and test (native)
      run: |
        cargo build --verbose
        cargo test --verbose

    - name: Build Linux release
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Build macOS release
      run: cargo build --release --target x86_64-apple-darwin

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: madu-linux
        path: target/x86_64-unknown-linux-gnu/release/madu

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: madu-macos
        path: target/x86_64-apple-darwin/release/madu